/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package views.ourServices;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import includes.OnlyDoubleDocumentFilter;
import includes.RegexValidator;

import models.ServicesModel;
import controllers.ServicesController;
import controllers.VehicleTypeController;
import includes.LoggerConfig;
import includes.OnlyLettersDocumentFilter;

import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author USER Keshan
 */
public class ServiceRegistration extends java.awt.Dialog {

    /**
     * Creates new form SupplierRegistration
     */
    private static final Logger logger = LoggerConfig.getLogger();

    private ourServicesJPanel parentPanel;

    public ServiceRegistration(java.awt.Frame parent, boolean modal, ourServicesJPanel parentPanel) {
        super(parent, modal);
        this.parentPanel = parentPanel;
        initComponents();
        setDocumentFilters();
        loadTypes();
    }

   
    private static HashMap<String, String> vehicleTypeMap = new HashMap<>();

    private void loadTypes() {

        try {

            ResultSet resultSet = new VehicleTypeController().show();

            Vector<String> vector = new Vector<>();
            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("name"));
                vehicleTypeMap.put(resultSet.getString("name"), resultSet.getString("id"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
            vehicle_type.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
            logger.severe("Error while loading types : " + e.getMessage());
        }
    }

    private void setDocumentFilters() {
        AbstractDocument doc = (AbstractDocument) Price.getDocument();
        doc.setDocumentFilter(new OnlyDoubleDocumentFilter());
        ((AbstractDocument) Service_name.getDocument()).setDocumentFilter(new OnlyLettersDocumentFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Service_name = new javax.swing.JTextField();
        service_register_btn = new javax.swing.JButton();
        service_reset_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        vehicle_type = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel1.setText("SERVICE REGISTRATION");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel3.setText("Service Name");

        Service_name.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Service_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Service_nameActionPerformed(evt);
            }
        });

        service_register_btn.setBackground(new java.awt.Color(33, 43, 108));
        service_register_btn.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        service_register_btn.setForeground(new java.awt.Color(255, 255, 255));
        service_register_btn.setText("REGISTER");
        service_register_btn.setBorderPainted(false);
        service_register_btn.setFocusPainted(false);
        service_register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service_register_btnActionPerformed(evt);
            }
        });

        service_reset_btn.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        service_reset_btn.setForeground(new java.awt.Color(255, 0, 0));
        service_reset_btn.setText("RESET");
        service_reset_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        service_reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service_reset_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setText("Price");

        vehicle_type.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setText("Vehicle Type");

        Price.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(service_reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(service_register_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Service_name, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(vehicle_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Price))))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Service_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vehicle_type, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(service_register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(service_reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog

        dispose();
    }//GEN-LAST:event_closeDialog

    private void service_register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service_register_btnActionPerformed

        String ServiceName = Service_name.getText();
        String VehicleType = String.valueOf(vehicle_type.getSelectedItem());
        String ServicePrice = Price.getText();
        double servicePrice = Double.parseDouble(ServicePrice);

        if (ServiceName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Service Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (VehicleType.equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please select a Vehicle Type", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (ServicePrice.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Service Price", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

        } //store
        try {
            ServicesModel servicesmodel = new ServicesModel();
            servicesmodel.setName(ServiceName);
            servicesmodel.setVehicleTypeId(Integer.parseInt(vehicleTypeMap.get(vehicle_type.getSelectedItem())));
            servicesmodel.setCharge(servicePrice);

            new ServicesController().store(servicesmodel);

            JOptionPane.showMessageDialog(this, "Service Registration Successfully");
            reset();

            // reload our services jpanel table
            parentPanel.reloadTable();

        } catch (Exception e) {
            e.printStackTrace();
            logger.severe("Error while storing service : " + e.getMessage());
        }

    }//GEN-LAST:event_service_register_btnActionPerformed

    private void service_reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service_reset_btnActionPerformed

        reset();
    }//GEN-LAST:event_service_reset_btnActionPerformed

    private void Service_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Service_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Service_nameActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//
//        FlatMacDarkLaf.setup();
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ServiceRegistration dialog = new ServiceRegistration(new java.awt.Frame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    private void reset() {

        Service_name.setText("");
        vehicle_type.setSelectedIndex(0);
        Price.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Service_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton service_register_btn;
    private javax.swing.JButton service_reset_btn;
    private javax.swing.JComboBox<String> vehicle_type;
    // End of variables declaration//GEN-END:variables
}
