/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package views.ourServices;

import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import includes.OnlyDoubleDocumentFilter;

import models.ServicesModel;
import controllers.ServicesController;
import controllers.VehicleTypeController;
import includes.LoggerConfig;

import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author USER Nimsara
 */
public class UpdateService extends java.awt.Dialog {
    
    private static final Logger logger = LoggerConfig.getLogger();

    private ServicesModel servicesModel;

    private ourServicesJPanel parentPanel;

    /**
     * Creates new form SupplierRegistration
     */
    public UpdateService(java.awt.Frame parent, boolean modal, ServicesModel servicesModel, ourServicesJPanel parentPanel) {
        super(parent, modal);
        this.servicesModel = servicesModel;
        this.parentPanel = parentPanel;
        initComponents();
        setDocumentFilters();
        loadTypes();
        setData();
    }

    private static HashMap<String, String> vehicleTypeMap = new HashMap<>();

    private void loadTypes() {
        try {
            ResultSet resultSet = new VehicleTypeController().show();

            Vector<String> vector = new Vector<>();
            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("name"));
                vehicleTypeMap.put(resultSet.getString("name"), resultSet.getString("id"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
            Vehicle_Type.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
            logger.severe("Error while loading types : "+e.getMessage());
        }
    }

    private void setDocumentFilters() {
        ((AbstractDocument) Service_Price.getDocument()).setDocumentFilter(new OnlyDoubleDocumentFilter());
    }

    private void setData() {
        Service_Name.setText(servicesModel.getName());

        // TODO : need to fix this
        Vehicle_Type.setSelectedItem(servicesModel.getVehicleTypeName());
        Service_Price.setText(String.valueOf(servicesModel.getCharge()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Service_Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Service_Price = new javax.swing.JTextField();
        Update_Service_btn = new javax.swing.JButton();
        customer_reset_btn = new javax.swing.JButton();
        Vehicle_Type = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel1.setText("UPDATE SERVICE");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Service Name");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Vehicle Category");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Price");
        jLabel7.setToolTipText("");

        Service_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Service_PriceActionPerformed(evt);
            }
        });

        Update_Service_btn.setBackground(new java.awt.Color(33, 43, 108));
        Update_Service_btn.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        Update_Service_btn.setForeground(new java.awt.Color(255, 255, 255));
        Update_Service_btn.setText("UPDATE");
        Update_Service_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Service_btnActionPerformed(evt);
            }
        });

        customer_reset_btn.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        customer_reset_btn.setForeground(new java.awt.Color(255, 0, 0));
        customer_reset_btn.setText("RESET");
        customer_reset_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        customer_reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_reset_btnActionPerformed(evt);
            }
        });

        Vehicle_Type.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Update_Service_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(customer_reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Service_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Service_Name)
                                    .addComponent(Vehicle_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Service_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vehicle_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Service_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update_Service_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void Update_Service_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Service_btnActionPerformed

        String ServiceName = Service_Name.getText();
        String VehicleType = String.valueOf(Vehicle_Type.getSelectedItem());
        String ServicePrice = Service_Price.getText();
        double servicePrice = Double.parseDouble(ServicePrice);

        if (ServiceName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter New Service Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (VehicleType.equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please select a New Vehicle Type", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (ServicePrice.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter New Service Price", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

        } //update
        try {
            servicesModel.setName(ServiceName);
            servicesModel.setVehicleTypeId(Integer.parseInt(vehicleTypeMap.get(Vehicle_Type.getSelectedItem())));
            servicesModel.setCharge(servicePrice);

            new ServicesController().update(servicesModel);

            JOptionPane.showMessageDialog(this, "Service Details Updated Successfully");
            reset();

            // relaod table
            parentPanel.reloadTable();
        } catch (Exception e) {
            e.printStackTrace();
            logger.severe("Error while updating service : "+e.getMessage());
        }

    }//GEN-LAST:event_Update_Service_btnActionPerformed

    private void Service_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Service_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Service_PriceActionPerformed

    private void customer_reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_reset_btnActionPerformed

        reset();
    }//GEN-LAST:event_customer_reset_btnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//
//        FlatMacDarkLaf.setup();
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                UpdateService dialog = new UpdateService(new java.awt.Frame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    private void reset() {

        Service_Name.setText("");
        Service_Price.setText("");
        Vehicle_Type.setSelectedIndex(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Service_Name;
    private javax.swing.JTextField Service_Price;
    private javax.swing.JButton Update_Service_btn;
    private javax.swing.JComboBox<String> Vehicle_Type;
    private javax.swing.JButton customer_reset_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
