/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.ourServices;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import controllers.ServicesController;


import controllers.VehicleTypeController;
import java.util.HashMap;

/**
 *
 * @author Keshan
 */
public class ViewService extends javax.swing.JFrame {

    /**
     * Creates new form ViewService
     */
    public ViewService() {
        initComponents();
        loadServices();
    }

    
    private void loadServices() {
        try {

            ResultSet serviceResultSet = new ServicesController().show();
            ResultSet servicesTypeResultSet = new VehicleTypeController().show();
          
           

            HashMap<Integer, String> VehicleTypeMap = new HashMap<>();
            
            while (servicesTypeResultSet.next()) {
                int vehicleTypeId = servicesTypeResultSet.getInt("id");
                String vehicleTypeName = servicesTypeResultSet.getString("name");
                VehicleTypeMap.put(vehicleTypeId, vehicleTypeName);
            }

            

            DefaultTableModel model = (DefaultTableModel) service_view_table.getModel();
            model.setRowCount(0);

            while (serviceResultSet.next()) {
                Vector<String> vector = new Vector<>();

                String serviceCode = serviceResultSet.getString("id");
                vector.add(serviceCode);
                vector.add(serviceResultSet.getString("name"));
                vector.add(serviceResultSet.getString("charge"));
                
                int vehicleTypeId = serviceResultSet.getInt("vehicle_type_id");
               

                String employeeTypeName = VehicleTypeMap.getOrDefault(vehicleTypeId, "Unknown Vehicle Type");
               

                vector.add(employeeTypeName);
               
                model.addRow(vector);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
     private void fetchService(String searchText) throws Exception {
        DefaultTableModel model = (DefaultTableModel) service_view_table.getModel();
        model.setRowCount(0);

        try {
            ResultSet resultSet = new ServicesController().search(searchText);
            ResultSet resultSet1 = new VehicleTypeController().search("");

            HashMap<Integer, String> vehicleTypeMap = new HashMap<>();
           

            while (resultSet1.next()) {
                int serviceTypeId = resultSet1.getInt("id");
                String vehicleTypeName = resultSet1.getString("name");
                vehicleTypeMap.put(serviceTypeId, vehicleTypeName);
            }

            while (resultSet.next()) {
                String id = resultSet.getString("id");
                String name = resultSet.getString("name");
                String charge = resultSet.getString("charge");
               
              
                int vehicleTypeId = resultSet.getInt("vehicle_type_id");

                String vehicleTypeName = vehicleTypeMap.getOrDefault(vehicleTypeId, "Unknown Type");

                model.addRow(new Object[]{id, name, charge});
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Add_Service_btn = new javax.swing.JButton();
        Update_Service_registration = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Service_Search_Bar = new javax.swing.JTextField();
        service_search_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        service_view_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 610));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("OUR SERVICES");

        Add_Service_btn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Add_Service_btn.setText("Add Service");
        Add_Service_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_Service_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Service_btnActionPerformed(evt);
            }
        });

        Update_Service_registration.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Update_Service_registration.setText("Update Service");
        Update_Service_registration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update_Service_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Service_registrationActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton3.setText("Delete Service");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add_Service_btn)
                .addGap(18, 18, 18)
                .addComponent(Update_Service_registration)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Service_btn)
                    .addComponent(Update_Service_registration)
                    .addComponent(jButton3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Service_Search_Bar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Service_Search_Bar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.gray));

        service_search_btn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        service_search_btn.setText("Search");
        service_search_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.gray));
        service_search_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        service_search_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                service_search_btnMouseClicked(evt);
            }
        });
        service_search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service_search_btnActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        service_view_table.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        service_view_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service Code", "Service Name", "Description", "Service Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        service_view_table.setCellSelectionEnabled(false);
        service_view_table.setEditingColumn(1);
        service_view_table.setEditingRow(1);
        service_view_table.setGridColor(new java.awt.Color(102, 102, 102));
        service_view_table.setRowHeight(50);
        jScrollPane1.setViewportView(service_view_table);
        service_view_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(Service_Search_Bar, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(service_search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 229, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(service_search_btn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Service_Search_Bar)
                        .addGap(1, 1, 1)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_Service_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Service_btnActionPerformed
        new ServiceRegistration(null, true).show();
    }//GEN-LAST:event_Add_Service_btnActionPerformed

    private void Update_Service_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Service_registrationActionPerformed
        new UpdateService(null, true).show();
    }//GEN-LAST:event_Update_Service_registrationActionPerformed

    private void service_search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service_search_btnActionPerformed

    }//GEN-LAST:event_service_search_btnActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        try {
            fetchService(null);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jPanel1ComponentShown

    private void service_search_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_service_search_btnMouseClicked
        try {
            fetchService(Service_Search_Bar.getText().toString());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_service_search_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new ViewService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Service_btn;
    private javax.swing.JTextField Service_Search_Bar;
    private javax.swing.JButton Update_Service_registration;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton service_search_btn;
    private javax.swing.JTable service_view_table;
    // End of variables declaration//GEN-END:variables
}
