/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.formdev.flatlaf.IntelliJTheme;
import java.awt.Toolkit;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;

/**
 *
 * @author kavindu
 */
public class SplashWindow extends javax.swing.JFrame {

    private static SplashWindow splashWindow;

    public static Logger ERROR_LOGGER = Logger.getLogger("Dazzle_Auto_Error_log");
    public static Logger GENERAL_LOGGER = Logger.getLogger("Dazzle_Auto_General_log");
    public static Logger ACTION_LOGGER = Logger.getLogger("Dazzle_Auto_Action_log");
    public static Logger ATTENDANCE_LOGGER = Logger.getLogger("Dazzle_Auto_Attendance_log");

    public SplashWindow() {
        splashWindow = this;
        initComponents();

        try {
            FileHandler errorfileHandler = new FileHandler("DA_Error_logger.log", true);
            errorfileHandler.setFormatter(new SimpleFormatter());

            FileHandler generalfileHandler = new FileHandler("DA_General_logger.log", true);
            generalfileHandler.setFormatter(new SimpleFormatter());

            FileHandler actionfileHandler = new FileHandler("DA_Action_logger.log", true);
            actionfileHandler.setFormatter(new SimpleFormatter());

            FileHandler attendancefileHandler = new FileHandler("DA_Attendance_logger.log", true);
            attendancefileHandler.setFormatter(new SimpleFormatter());

            ERROR_LOGGER.addHandler(errorfileHandler);
            GENERAL_LOGGER.addHandler(generalfileHandler);
            ACTION_LOGGER.addHandler(actionfileHandler);
            ATTENDANCE_LOGGER.addHandler(attendancefileHandler);
        } catch (Exception e) {
            e.printStackTrace();
            ERROR_LOGGER.log(Level.SEVERE, "Exception In Logger FileHandler", e);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon("src/resources/loading-animation2.gif"));
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/resources/icon2.png")));
        lodingAnimation();
    }

    //Progress Bar Code
    private void lodingAnimation() {
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {
                    ProgressBar.setValue(i);
                    try {
                        Thread.sleep(10);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

                splashWindow.dispose();
                new LoginChooser().setVisible(true);
            }
        });
        thread.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ProgressBar.setForeground(new java.awt.Color(241, 145, 8));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    public static void main(String args[]) {
//        
//        IntelliJTheme.setup(SplashWindow.class.getResourceAsStream(
//                    "/resources/themes/arc-theme.theme.json"));
//
//        
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                splashWindow = new SplashWindow();
//                splashWindow.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
