/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package views.customer;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import includes.OnlyNumbersDocumentFilter;
import includes.RegexValidator;
import includes.TimestampsGenerator;
import java.sql.ResultSet;
import controllers.CustomerController;
import includes.LoggerConfig;
import includes.OnlyLettersDocumentFilter;
import java.awt.Frame;
import java.awt.Toolkit;
import java.util.logging.Logger;
import models.CustomerModel;

/**
 *
 * @author USER Nimsara
 */
public class CustomerRegistration extends java.awt.Dialog {

    private static final Logger logger = LoggerConfig.getLogger();

    private CustomerJPanel customerJPanel;

    /**
     * Creates new form SupplierRegistration
     */
    public CustomerRegistration(Frame parent, boolean modal, CustomerJPanel customerJPanel) {
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/resources/icon2.png")));
        setDocumentFilters();

//        this.customerJPanel = customerJPanel;
        this.customerJPanel = customerJPanel;

    }

    private void setDocumentFilters() {
        ((AbstractDocument) customer_mobile.getDocument()).setDocumentFilter(new OnlyNumbersDocumentFilter());
        ((AbstractDocument) customer_firstname.getDocument()).setDocumentFilter(new OnlyLettersDocumentFilter());
        ((AbstractDocument) customer_lastname.getDocument()).setDocumentFilter(new OnlyLettersDocumentFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customer_firstname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        customer_lastname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        customer_mobile = new javax.swing.JTextField();
        customer_register_btn = new javax.swing.JButton();
        customer_reset_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        customer_email = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel1.setText("CUSTOMER REGISTRATION");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel3.setText("First Name");

        customer_firstname.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel4.setText("Last Name");

        customer_lastname.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setText("Mobile");

        customer_mobile.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        customer_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_mobileActionPerformed(evt);
            }
        });

        customer_register_btn.setBackground(new java.awt.Color(33, 43, 108));
        customer_register_btn.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        customer_register_btn.setForeground(new java.awt.Color(255, 255, 255));
        customer_register_btn.setText("REGISTER");
        customer_register_btn.setBorderPainted(false);
        customer_register_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customer_register_btn.setFocusPainted(false);
        customer_register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_register_btnActionPerformed(evt);
            }
        });

        customer_reset_btn.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        customer_reset_btn.setForeground(new java.awt.Color(255, 0, 0));
        customer_reset_btn.setText("RESET");
        customer_reset_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        customer_reset_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customer_reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_reset_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setText("Email");

        customer_email.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(customer_reset_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customer_register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customer_firstname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customer_lastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customer_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customer_mobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customer_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customer_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void customer_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_mobileActionPerformed

    private void customer_register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_register_btnActionPerformed
        String firstName = customer_firstname.getText();
        String lastName = customer_lastname.getText();
        String mobile = customer_mobile.getText();
        String email = customer_email.getText();

        if (firstName.isEmpty()) {
            showWarningMessage("Please enter your first name");
        } else if (lastName.isEmpty()) {
            showWarningMessage("Please enter your last name");
        } else if (mobile.isEmpty()) {
            showWarningMessage("Please enter your mobile number");
        } else if (!RegexValidator.isValidSlPhone(mobile)) {
            showWarningMessage("Invalid mobile number! (Ex: 0771234567)");
        } else if (email.isEmpty()) {
            showWarningMessage("Please enter your email");
        } else if (!RegexValidator.isValidEmail(email)) {
            showWarningMessage("Invalid email format!");
        } else {
            // Setup CustomerModel
            CustomerModel customerModel = new CustomerModel();
            customerModel.setFirstName(firstName);
            customerModel.setLastName(lastName);
            customerModel.setMobile(mobile);
            customerModel.setEmail(email);

            String registerDateTime = TimestampsGenerator.getFormattedDateTime();
            customerModel.setRegisteredDate(registerDateTime);

            // Check if the customer already exists
            // Proceed to register the customer
            try {
                ResultSet resultSet = new CustomerController().store(customerModel);
                JOptionPane.showMessageDialog(this, "Customer Registered Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                reset();
            } catch (Exception e) {
                e.printStackTrace();
                logger.severe("Error while registering a customer: " + e.getMessage());
            }

            customerJPanel.reloadTable();

        }


    }//GEN-LAST:event_customer_register_btnActionPerformed
    private boolean isThisCustomerAlreadyExists(String mobile, String email) {
        try {
            ResultSet resultSet = new CustomerController().show();
            if (resultSet.next()) {
                return true;
            }
        } catch (Exception e) {
            logger.severe("Error while load vehicle by number : " + e.getMessage());
        }
        return false;
    }

    private void showWarningMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Warning", JOptionPane.WARNING_MESSAGE);
    }

    private void customer_reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_reset_btnActionPerformed

        reset();

    }//GEN-LAST:event_customer_reset_btnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//
//        FlatMacDarkLaf.setup();
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CustomerRegistration dialog = new CustomerRegistration(new java.awt.Frame(), true, customerJPanel);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    private void reset() {

        customer_firstname.setText("");
        customer_lastname.setText("");
        customer_mobile.setText("");
        customer_email.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customer_email;
    private javax.swing.JTextField customer_firstname;
    private javax.swing.JTextField customer_lastname;
    private javax.swing.JTextField customer_mobile;
    private javax.swing.JButton customer_register_btn;
    private javax.swing.JButton customer_reset_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
